const testTexts = [
//   "The quick brown fox jumps over the lazy dog near the riverbank.",
//   "Programming is the art of telling a computer what to do through code.",
//   "Practice makes perfect, and typing speed improves with daily exercise.",
//   "Technology has transformed the way we live, work, and communicate.",
//   "Learning to type fast and accurately is an essential skill in the digital age.",
//   "The Internet has revolutionized information sharing and global connectivity.",
//   "Success is not final, failure is not fatal: it is the courage to continue that counts.",
//   "In the middle of difficulty lies opportunity waiting to be discovered.",
//   "Life is what happens when you are busy making other plans for the future.",
//   "The only way to do great work is to love what you do every single day.",
//   "Innovation distinguishes between a leader and a follower in any industry.",
//   "Stay hungry, stay foolish, and never stop learning new things.",
//   "The best time to plant a tree was twenty years ago, the second best is now.",
//   "Quality is not an act, it is a habit that we develop over time.",
//   "The journey of a thousand miles begins with a single step forward.",
//   "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
//   "The only limit to our realization of tomorrow will be our doubts of today.",
//   "Do what you can, with what you have, where you are at this moment.",
//   "Everything you have ever wanted is on the other side of fear.",
//   "The greatest glory in living lies not in never falling, but in rising every time we fall.",
//   "Your time is limited, so do not waste it living someone else's life.",
//   "The best revenge is massive success against all odds.",
//   "Well done is better than well said in every situation.",
//   "Happiness is not something ready made, it comes from your own actions.",
//   "The only person you are destined to become is the person you decide to be.",
//   "No one can make you feel inferior without your consent or permission.",
//   "If you want to lift yourself up, lift up someone else first.",
//   "The future belongs to those who believe in the beauty of their dreams.",
//   "It is during our darkest moments that we must focus to see the light.",
//   "Act as if what you do makes a difference because it actually does.",
//   "What you do today can improve all your tomorrows significantly.",
//   "The secret of getting ahead is getting started with small steps.",
//   "Either you run the day or the day runs you and your schedule.",
//   "Dream big and dare to fail is the path to true achievement.",
//   "What we think, we become through our consistent actions.",
//   "A goal without a plan is just a wish waiting to be fulfilled.",
//   "The best preparation for tomorrow is doing your best today.",
//   "Do not let what you cannot do interfere with what you can do.",
//   "Believe you can and you are halfway there already.",
//   "Success usually comes to those who are too busy to be looking for it.",
//   "The only impossible journey is the one you never begin.",
//   "Opportunities do not happen, you create them through effort.",
//   "Do not wait for opportunity, create it with your own hands.",
//   "The harder you work for something, the greater you will feel when you achieve it.",
//   "Dream it, wish it, do it, and make it happen.",
//   "Great things never come from comfort zones and complacency.",
//   "Success is not about the destination but the journey itself.",
//   "Small steps in the right direction can turn out to be the biggest step of your life.",
//   "The biggest adventure you can take is to live the life of your dreams.",
//   "Your life only gets better when you do, so start improving today.",
//   "Do not be pushed by your problems, be led by your dreams and aspirations.",
  "In the world of software development, writing clean, maintainable code is just as important as solving complex problems efficiently and effectively.",
  "The ability to communicate clearly and concisely is a fundamental skill that opens doors to countless opportunities in every professional field.",
  "As technology continues to evolve at an unprecedented pace, lifelong learning has become not just an option but a necessity for everyone.",
  "Building meaningful relationships and fostering strong teamwork are essential components of achieving long-term success in any organization.",
  "The pursuit of knowledge and understanding is a journey that never truly ends, and each step along the way brings new insights and growth.",
  "Effective time management combined with consistent effort creates the foundation upon which all great achievements are built and sustained.",
  "Creativity thrives when we allow ourselves to think differently, challenge assumptions, and embrace the unknown with courage and curiosity.",
  "Every challenge we face is an opportunity to learn, grow, and become stronger versions of ourselves if we choose to embrace it fully.",
  "The power of positive thinking and a resilient mindset can transform even the most difficult situations into stepping stones for future success.",
  "Mastering the art of active listening and empathetic communication strengthens our connections with others and enriches our personal lives.",
  "In the digital age, protecting our privacy and security online has become increasingly important as we navigate an interconnected world.",
  "The discipline of daily practice, even when motivation is low, is what separates those who achieve their goals from those who only dream about them."
];
